apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dws-event-frontend-ingress
  namespace: dws-frontend
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  rules:
  - host: frontend.ltu-m7011e-6.se
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dws-event-frontend
            port:
              number: 80
  tls:
  - hosts:
    - frontend.ltu-m7011e-6.se
    secretName: dws-frontend-tls