apiVersion: v1
kind: Service
metadata:
  name: dws-event-frontend
  namespace: dws-frontend
  labels:
    app: dws-event-frontend
spec:
  type: ClusterIP
  selector:
    app: dws-event-frontend
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http